# Generated by Django 6.0.1 on 2026-02-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_otp_code_user_otp_expires_at_user_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.RemoveField(
            model_name='address',
            name='created_at',
        ),
        migrations.AddField(
            model_name='wallet',
            name='loyalty_points',
            field=models.IntegerField(default=0),
        ),
    ]
