# Generated by Django 6.0.1 on 2026-06-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_address_options_remove_address_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('manager', 'Manager'), ('staff', 'Staff'), ('delivery', 'Delivery'), ('marketing', 'Marketing')], default='user', max_length=10),
        ),
    ]
