#!/usr/bin/env bash
# ============================================================
# GlowElle BD — VPS Auto Setup Script
# Ubuntu 22.04 / 24.04
# Run: bash setup_vps.sh
# ============================================================

set -e

# ---- Colors ----
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

info()    { echo -e "${GREEN}[INFO]${NC} $1"; }
warn()    { echo -e "${YELLOW}[WARN]${NC} $1"; }
error()   { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }

# ============================================================
# 1. CONFIG — শুধু এই অংশ পরিবর্তন করো
# ============================================================
DB_NAME="glowellebd"
DB_USER="glowelle_user"
DB_PASS="GlowElle@2025Secure"          # শক্তিশালী password দাও
PROJECT_DIR="/var/www/glowellebd"
DOMAIN="yourdomain.com"                # তোমার domain বা VPS IP
SECRET_KEY="change-this-to-a-very-long-random-secret-key-50chars+"
# ============================================================

info "=== GlowElle BD VPS Setup শুরু হচ্ছে ==="

# ---- System Update ----
info "System update করা হচ্ছে..."
apt-get update -qq && apt-get upgrade -y -qq

# ---- Dependencies Install ----
info "Dependencies install করা হচ্ছে..."
apt-get install -y -qq \
    python3 python3-pip python3-venv \
    postgresql postgresql-contrib \
    nginx \
    git curl wget \
    libpq-dev python3-dev \
    build-essential

# ============================================================
# 2. PostgreSQL Setup — Auto Database তৈরি
# ============================================================
info "PostgreSQL database তৈরি করা হচ্ছে..."

# PostgreSQL service চালু করো
systemctl start postgresql
systemctl enable postgresql

# Database এবং User তৈরি করো (already থাকলে skip)
sudo -u postgres psql -tc "SELECT 1 FROM pg_roles WHERE rolname='${DB_USER}'" | grep -q 1 || \
    sudo -u postgres psql -c "CREATE USER ${DB_USER} WITH PASSWORD '${DB_PASS}';"

sudo -u postgres psql -tc "SELECT 1 FROM pg_database WHERE datname='${DB_NAME}'" | grep -q 1 || \
    sudo -u postgres psql -c "CREATE DATABASE ${DB_NAME} OWNER ${DB_USER};"

sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE ${DB_NAME} TO ${DB_USER};"

info "Database '${DB_NAME}' তৈরি হয়েছে!"

# ============================================================
# 3. Project Setup
# ============================================================
info "Project directory তৈরি করা হচ্ছে: ${PROJECT_DIR}"
mkdir -p "${PROJECT_DIR}"

# যদি git repo থেকে clone করতে চাও — uncomment করো:
# info "Code clone করা হচ্ছে..."
# git clone https://github.com/your-username/glowellebd.git "${PROJECT_DIR}"

# ---- Virtual Environment ----
info "Python virtual environment তৈরি করা হচ্ছে..."
cd "${PROJECT_DIR}"
python3 -m venv venv
source venv/bin/activate

# ---- Dependencies Install ----
info "Python packages install করা হচ্ছে..."
pip install --upgrade pip -q
pip install -r requirements.txt -q

# ============================================================
# 4. .env File Auto তৈরি
# ============================================================
info ".env file তৈরি করা হচ্ছে..."

# DATABASE_URL তৈরি
DATABASE_URL="postgresql://${DB_USER}:${DB_PASS}@localhost:5432/${DB_NAME}"

# .env file লেখো (আগেরটা থাকলে backup নাও)
if [ -f "${PROJECT_DIR}/.env" ]; then
    cp "${PROJECT_DIR}/.env" "${PROJECT_DIR}/.env.backup"
    warn ".env backup নেওয়া হয়েছে: .env.backup"
fi

cat > "${PROJECT_DIR}/.env" << EOF
# ============================================
# GlowElle BD — Production Environment
# Auto-generated by setup_vps.sh
# ============================================

SECRET_KEY=${SECRET_KEY}
DEBUG=False
ALLOWED_HOSTS=${DOMAIN},www.${DOMAIN},localhost,127.0.0.1
SITE_URL=https://${DOMAIN}

# Database (Auto-configured)
DATABASE_URL=${DATABASE_URL}

# MongoDB (পরিবর্তন করো)
MONGODB_URI=mongodb+srv://Shop:Shop123456@shop.xtmkurh.mongodb.net/?appName=Shop
MONGODB_NAME=shop_db

# Email (Gmail credentials দাও)
EMAIL_HOST_USER=your-gmail@gmail.com
EMAIL_HOST_PASSWORD=your-gmail-app-password
DEFAULT_FROM_EMAIL=GlowElle BD <noreply@glowellebd.com>

# AI Keys (পরিবর্তন করো)
GEMINI_API_KEY=your-gemini-key
OPENAI_API_KEY=your-openai-key

# Cloudinary (পরিবর্তন করো)
CLOUDINARY_CLOUD_NAME=your-cloud-name
CLOUDINARY_API_KEY=your-api-key
CLOUDINARY_API_SECRET=your-api-secret

# Security
SECURE_SSL_REDIRECT=True
SESSION_COOKIE_SECURE=True
CSRF_COOKIE_SECURE=True
EOF

info ".env file তৈরি হয়েছে!"

# ============================================================
# 5. Django Setup — Migrate + Static
# ============================================================
info "Django migrations চালানো হচ্ছে..."
python manage.py migrate --no-input

info "Static files collect করা হচ্ছে..."
python manage.py collectstatic --no-input

# Superuser তৈরি (auto — admin/admin123, পরে পরিবর্তন করো)
info "Django superuser তৈরি করা হচ্ছে..."
echo "from django.contrib.auth import get_user_model; \
U = get_user_model(); \
U.objects.filter(username='admin').exists() or \
U.objects.create_superuser('admin', 'admin@glowellebd.com', 'admin123')" \
| python manage.py shell

warn "Admin password 'admin123' — login করে সাথে সাথে পরিবর্তন করো!"

# ============================================================
# 6. Gunicorn Service তৈরি (Auto Start)
# ============================================================
info "Gunicorn systemd service তৈরি করা হচ্ছে..."

cat > /etc/systemd/system/glowellebd.service << EOF
[Unit]
Description=GlowElle BD Django App
After=network.target postgresql.service

[Service]
User=www-data
Group=www-data
WorkingDirectory=${PROJECT_DIR}
EnvironmentFile=${PROJECT_DIR}/.env
ExecStart=${PROJECT_DIR}/venv/bin/gunicorn \
    --workers 2 \
    --bind unix:${PROJECT_DIR}/glowellebd.sock \
    config.wsgi:application
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl start glowellebd
systemctl enable glowellebd

# ============================================================
# 7. Nginx Config
# ============================================================
info "Nginx configure করা হচ্ছে..."

cat > /etc/nginx/sites-available/glowellebd << EOF
server {
    listen 80;
    server_name ${DOMAIN} www.${DOMAIN};

    location = /favicon.ico { access_log off; log_not_found off; }

    location /static/ {
        alias ${PROJECT_DIR}/staticfiles/;
    }

    location /media/ {
        alias ${PROJECT_DIR}/media/;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:${PROJECT_DIR}/glowellebd.sock;
    }
}
EOF

ln -sf /etc/nginx/sites-available/glowellebd /etc/nginx/sites-enabled/
nginx -t && systemctl restart nginx

# ============================================================
# Done!
# ============================================================
echo ""
echo -e "${GREEN}============================================${NC}"
echo -e "${GREEN}  GlowElle BD Setup সম্পন্ন!${NC}"
echo -e "${GREEN}============================================${NC}"
echo ""
echo -e "  Database   : ${GREEN}${DB_NAME}${NC}"
echo -e "  DB User    : ${GREEN}${DB_USER}${NC}"
echo -e "  Project    : ${GREEN}${PROJECT_DIR}${NC}"
echo -e "  Site URL   : ${GREEN}http://${DOMAIN}${NC}"
echo ""
echo -e "${YELLOW}এখন করো:${NC}"
echo -e "  1. ${PROJECT_DIR}/.env খুলে API keys ও email দাও"
echo -e "  2. Admin panel: http://${DOMAIN}/admin (admin / admin123)"
echo -e "  3. Admin password পরিবর্তন করো!"
echo -e "  4. SSL এর জন্য: certbot --nginx -d ${DOMAIN}"
echo ""
