# Generated by Django 6.0 on 2025-12-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='Nyveralife', max_length=200)),
                ('meta_description', models.TextField(blank=True, help_text='SEO description for the homepage')),
                ('ga4_tracking_id', models.CharField(blank=True, help_text='e.g., G-XXXXXXXXXX', max_length=50)),
                ('search_console_code', models.CharField(blank=True, help_text='Google verification code', max_length=100)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('support_phone', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
