# Generated by Django 6.0.1 on 2026-02-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='Common user question', max_length=255)),
                ('keywords', models.CharField(help_text='Comma-separated keywords to trigger this answer', max_length=255)),
                ('answer', models.TextField(help_text='The response the chatbot should give')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chatbot FAQ',
                'verbose_name_plural': 'Chatbot FAQs',
                'ordering': ['question'],
            },
        ),
        migrations.CreateModel(
            name='ChatbotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_message', models.TextField(default='👋 Hi! Welcome to GlowElle! How can I help you today?', help_text='First message shown when the chat opens')),
                ('system_prompt', models.TextField(default="You are 'GlowElle Assistant'. Be helpful, confident, and professional. Use product data provided. Guarantee 100% freshness.", help_text='Global instructions for the AI brain')),
                ('not_found_message', models.TextField(default="I couldn't find a specific answer for that. Would you like to talk to a human agent?", help_text='Fall-back message when no FAQ or product matches')),
            ],
            options={
                'verbose_name': 'Chatbot Settings',
                'verbose_name_plural': 'Chatbot Settings',
            },
        ),
    ]
