# Generated by Django 6.0.1 on 2026-02-02 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_chatbotfaq_chatbotsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent_key', models.CharField(help_text="The internal key (e.g., 'buying', 'support')", max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('keywords', models.TextField(help_text='Comma-separated keywords to trigger this intent')),
            ],
        ),
        migrations.CreateModel(
            name='ChatbotSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text="Button text (e.g., 'Popular Items')", max_length=50)),
                ('action', models.CharField(default='message', help_text='Action type (message/url)', max_length=50)),
                ('value', models.CharField(blank=True, help_text='Value for the action (e.g., the message to send)', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Chatbot Suggestion',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='is_promo_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='offline_message',
            field=models.TextField(default='Our support team is currently offline. Please leave your message and we will get back to you during working hours (9 AM - 10 PM).', help_text='Message shown when user asks for human support outside working hours'),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='promo_message',
            field=models.TextField(blank=True, help_text="Special offer or announcement (e.g., '10% off on all fruits today!')"),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='working_hours_end',
            field=models.TimeField(default='22:00', help_text='Support end time (e.g., 22:00)'),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='working_hours_start',
            field=models.TimeField(default='09:00', help_text='Support start time (e.g., 09:00)'),
        ),
    ]
