# Generated by Django 6.0.1 on 2026-02-02 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_chatbotintent_chatbotsuggestion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatbotintent',
            options={'verbose_name': 'Chatbot Intent', 'verbose_name_plural': 'Chatbot Intents'},
        ),
    ]
