# Generated by Django 6.0.1 on 2026-02-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_chatbotintent_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='meta_description',
            field=models.TextField(blank=True, default='Your one-stop shop for fresh organic fruits, vegetables, meat, and daily essentials.', help_text='SEO description for the homepage'),
        ),
    ]
