# Generated by Django 6.0.1 on 2026-02-02 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_sitesettings_meta_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatbotFAQ',
        ),
        migrations.DeleteModel(
            name='ChatbotIntent',
        ),
        migrations.DeleteModel(
            name='ChatbotSettings',
        ),
        migrations.DeleteModel(
            name='ChatbotSuggestion',
        ),
    ]
