# Generated by Django 6.0.1 on 2026-02-02 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='Common user question', max_length=255)),
                ('keywords', models.CharField(help_text='Comma-separated keywords to trigger this answer', max_length=255)),
                ('answer', models.TextField(help_text='The response the chatbot should give')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chatbot FAQ',
                'verbose_name_plural': 'Chatbot FAQs',
                'db_table': 'core_chatbotfaq',
                'ordering': ['question'],
            },
        ),
        migrations.CreateModel(
            name='ChatbotIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent_key', models.CharField(help_text="The internal key (e.g., 'buying', 'support')", max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('keywords', models.TextField(help_text='Comma-separated keywords to trigger this intent')),
            ],
            options={
                'verbose_name': 'Chatbot Intent',
                'verbose_name_plural': 'Chatbot Intents',
                'db_table': 'core_chatbotintent',
            },
        ),
        migrations.CreateModel(
            name='ChatbotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_message', models.TextField(default='👋 Hi! Welcome to Nyveralife! How can I help you today?', help_text='First message shown when the chat opens')),
                ('system_prompt', models.TextField(default="You are 'Nyveralife Assistant'. Be helpful, confident, and professional. Use product data provided. Guarantee 100% freshness.", help_text='Global instructions for the AI brain')),
                ('not_found_message', models.TextField(default="I couldn't find a specific answer for that. Would you like to talk to a human agent?", help_text='Fall-back message when no FAQ or product matches')),
                ('working_hours_start', models.TimeField(default='09:00', help_text='Support start time (e.g., 09:00)')),
                ('working_hours_end', models.TimeField(default='22:00', help_text='Support end time (e.g., 22:00)')),
                ('offline_message', models.TextField(default='Our support team is currently offline. Please leave your message and we will get back to you during working hours (9 AM - 10 PM).', help_text='Message shown when user asks for human support outside working hours')),
                ('promo_message', models.TextField(blank=True, help_text="Special offer or announcement (e.g., '10% off on all fruits today!')")),
                ('is_promo_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Chatbot Settings',
                'verbose_name_plural': 'Chatbot Settings',
                'db_table': 'core_chatbotsettings',
            },
        ),
        migrations.CreateModel(
            name='ChatbotSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text="Button text (e.g., 'Popular Items')", max_length=50)),
                ('action', models.CharField(default='message', help_text='Action type (message/url)', max_length=50)),
                ('value', models.CharField(blank=True, help_text='Value for the action (e.g., the message to send)', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Chatbot Suggestion',
                'db_table': 'core_chatbotsuggestion',
                'ordering': ['order'],
            },
        ),
    ]
