# Generated by Django 6.0.1 on 2026-02-02 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotConversationMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, help_text='Unique session identifier', max_length=255)),
                ('user_message', models.TextField(help_text="User's message")),
                ('bot_response', models.TextField(help_text="Bot's response")),
                ('detected_intent', models.CharField(blank=True, help_text='Detected intent (greeting, product_query, etc.)', max_length=50)),
                ('user_preferences', models.JSONField(blank=True, default=dict, help_text='User preferences like last_product, language, etc.')),
                ('greeting_count', models.IntegerField(default=0, help_text='Number of times user greeted in this session')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Conversation Memory',
                'verbose_name_plural': 'Conversation Memories',
                'db_table': 'chatbot_conversation_memory',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_id', '-created_at'], name='session_created_idx')],
            },
        ),
    ]
