# Generated by Django 6.0.1 on 2026-02-02 21:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chatbotconversationmemory'),
        ('orders', '0016_alter_orderstatushistory_options'),
        ('products', '0015_review_image_review_is_verified_purchase_stockalert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now, unique=True)),
                ('total_conversations', models.IntegerField(default=0, help_text='Total chat sessions started')),
                ('total_messages', models.IntegerField(default=0, help_text='Total messages exchanged')),
                ('total_orders', models.IntegerField(default=0, help_text='Orders placed via chatbot')),
                ('conversion_rate', models.FloatField(default=0.0, help_text='Percentage of chats that resulted in orders')),
                ('average_messages_per_session', models.FloatField(default=0.0)),
                ('unique_users', models.IntegerField(default=0, help_text='Unique users who chatted')),
            ],
            options={
                'verbose_name': 'Chatbot Analytics',
                'verbose_name_plural': 'Chatbot Analytics',
                'db_table': 'chatbot_analytics',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='chatbotintent',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this intent is active'),
        ),
        migrations.CreateModel(
            name='ChatbotMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=255)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('messages_count', models.IntegerField(default=0)),
                ('resulted_in_order', models.BooleanField(default=False)),
                ('user_rating', models.IntegerField(blank=True, help_text='1-5 stars', null=True)),
                ('detected_intents', models.JSONField(blank=True, default=list, help_text='List of intents detected')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Session Metric',
                'verbose_name_plural': 'Chat Session Metrics',
                'db_table': 'chatbot_metrics',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['session_id', '-started_at'], name='session_time_idx'), models.Index(fields=['resulted_in_order', '-started_at'], name='order_time_idx')],
            },
        ),
        migrations.CreateModel(
            name='PopularProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('query_count', models.IntegerField(default=0, help_text='Times queried in chatbot')),
                ('order_count', models.IntegerField(default=0, help_text='Times ordered via chatbot')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name': 'Popular Product',
                'verbose_name_plural': 'Popular Products',
                'db_table': 'chatbot_popular_products',
                'ordering': ['-date', '-query_count'],
                'unique_together': {('product', 'date')},
            },
        ),
    ]
