# Generated by Django 6.0.1 on 2026-01-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealOfTheDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Deal of the Day', max_length=255)),
                ('subtitle', models.CharField(blank=True, help_text='e.g. Get up to 50% OFF...', max_length=500, null=True)),
                ('image', models.ImageField(help_text='Background Banner Image (Recommended: 1000x400px)', upload_to='deals/')),
                ('discount_percentage', models.IntegerField(default=0, help_text='e.g. 50')),
                ('end_date', models.DateTimeField(help_text='Countdown will end at this time')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
