# Generated by Django 6.0.1 on 2026-02-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_dealoftheday'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, help_text='e.g. On orders over ৳1000', max_length=255, null=True)),
                ('icon', models.CharField(help_text='Lucide icon name (e.g., truck, headset, shield-check, undo-2, leaf, award)', max_length=50)),
                ('sort_order', models.IntegerField(default=0, help_text='Lower numbers appear first')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Selling Note',
                'verbose_name_plural': 'Selling Notes',
                'ordering': ['sort_order'],
            },
        ),
    ]
