# Generated by Django 6.0.1 on 2026-06-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_sellingnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeslider',
            name='subtitle',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
