# Generated by Django 6.0 on 2025-12-08 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_add_courier'),
        ('orders', '0003_alter_order_payment_method'),
    ]

    operations = [
    ]
