# Generated by Django 6.0 on 2025-12-22 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_actual_delivery_date_order_billing_address_and_more'),
        ('users', '0003_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_download_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='support_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='users.supportticket'),
        ),
    ]
