# Generated by Django 6.0 on 2025-12-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_invoice_download_count_order_support_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='stock_at_order',
            field=models.IntegerField(blank=True, help_text='Stock quantity at the time of order', null=True),
        ),
    ]
