# Generated by Django 6.0 on 2025-12-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_orderitem_stock_at_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='automation_logs',
            field=models.TextField(blank=True, help_text='JSON or text logs of automation', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='credit_note_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_confirmation_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='is_delivery_update_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_method',
            field=models.CharField(blank=True, help_text='e.g. bKash, Bank Transfer', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='return_status',
            field=models.CharField(choices=[('none', 'None'), ('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='none', max_length=20),
        ),
    ]
