# Generated by Django 6.0.1 on 2026-02-02 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_orderitem_variant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderstatushistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Order Status History', 'verbose_name_plural': 'Order Status History'},
        ),
    ]
