# Generated by Django 6.0 on 2025-12-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Image for social media sharing', max_length=255, null=True, upload_to='seo/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='products/main/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Image for social media sharing', max_length=255, null=True, upload_to='seo/'),
        ),
    ]
