# Generated by Django 6.0.1 on 2026-01-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_prod_cat_created_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.TextField(blank=True, help_text='Short summary of the product (300-500 chars)', max_length=500, null=True),
        ),
    ]
