# Generated by Django 6.0.1 on 2026-02-02 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='chatbot_priority',
            field=models.BooleanField(default=False, help_text='Prioritize this product in chatbot responses'),
        ),
    ]
